### PR TITLE
Various minor improvements 

### PR DESCRIPTION
**Pull request by HorlogeSkynet**
Hey all,

I know the v4.5.0 went out not a long time ago but there were some stuffs I'd like to fix for the future.

## Description

* README (not relevant here)
* I've experienced a glitch yesterday with GPU info on an odd case, this should be fixed with the brought changes
* I've noticed we don't use the first value of a tuple on the very same class, so this has been removed as well
* :warning: **[WIP] There are some `ResourcesWarning` thrown during test cases. It would be cool if someone could look into it, in order to fix either Archey sources or its test cases as needed (I can't figure out a way to close the pending resources...).** :warning: 

## Reason and / or context

Get the documentation and the test cases clean, improve performances and readability and handles new odd cases.

## How has this been tested ?

Debian, test cases...

## Types of changes :

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Typo / style fix (non-breaking change which improves readability)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist :

- [X] \[IF NEEDED\] I have updated the _README.md_ file accordingly ;
- [x] \[IF NEEDED\] I have updated the test cases (which pass) accordingly ;
- [X] My change looks good ;
- [X] I agree that my code may be modified in the future ;
- [X] My code follows the code style of this project ([PEP8](https://www.python.org/dev/peps/pep-0008/)).

### CODE REVIEW

**Comment by HorlogeSkynet** [comment]
Below are the remaining warnings to fix :

```
test_manual_workaround (test.test_archey_lan_ip_manual.TestLanIpEntryManual) ...
/opt/python/3.7-dev/lib/python3.7/subprocess.py:810: ResourceWarning: subprocess 1854 is still running
  ResourceWarning, source=self)
/opt/python/3.7-dev/lib/python3.7/subprocess.py:810: ResourceWarning: subprocess 1855 is still running
  ResourceWarning, source=self)
/opt/python/3.7-dev/lib/python3.7/subprocess.py:810: ResourceWarning: subprocess 1856 is still running
  ResourceWarning, source=self)

test_manual_workaround_limit (test.test_archey_lan_ip_manual.TestLanIpEntryManual) ... /opt/python/3.7-dev/lib/python3.7/subprocess.py:810: ResourceWarning: subprocess 1858 is still running
  ResourceWarning, source=self)
/opt/python/3.7-dev/lib/python3.7/subprocess.py:810: ResourceWarning: subprocess 1859 is still running
  ResourceWarning, source=self)
/opt/python/3.7-dev/lib/python3.7/subprocess.py:810: ResourceWarning: subprocess 1860 is still running
  ResourceWarning, source=self)
ok
```

**Comment by Si13n7** [comment]
I'll test that later, but I'm not sure if I can help you here... 🤔

**Comment by HorlogeSkynet** [comment]
No problem Roy, the only thing that could break something is the REGEXP change for GPU.
I'll try to handle the remaining warnings on my own, don't bother :+1:

**Comment by HorlogeSkynet** [comment]
Ahah thanks Roy :ok_hand: 
Don't worry about the tests, I'll look into it again in a few days, but if I can't manage to silence the remaining warnings, it's gonna stay that way :smile:

**Comment by HorlogeSkynet** [comment]
For information and the future (maybe), below you can check the remaining warnings occurring during tests :

* https://travis-ci.org/HorlogeSkynet/archey4/jobs/411355006 (Python 3.6)
* https://travis-ci.org/HorlogeSkynet/archey4/jobs/411355007 (Python 3.7-dev)

We'll ignore them at the moment, as they are only involved within test environment, and more precisely, around the `check_output` mock file descriptors.

Bye :wave:

**Pull request merged**
