### PR TITLE
[FEATURE] Implements a `-s` option to make Archey take a screenshot

### PR DESCRIPTION
**Pull request by HorlogeSkynet**
Title should be self-explanatory :smile:

## Description

New CLI option/argument.
Implemented logic wants to be EAFP, handling many different cases in a "best-effort" fashion.
One may want to add its specific (omitted ?) program to the supported list (really easy).

:warning: Important note : Sometimes it's not possible to directly specify the output filename. In such cases, the targeted directory should be honored.

:warning: Important note (2) : This feature will be considered as a "soft-extension" of Archey, so no screenshot program has been (and will be) added to required/optional dependencies lists.

:warning: Important note (3) : It's a first very basic implementation, it might evolve in the future.

Thanks :bow:

## Reason and / or context

Well, ScreenFetch supports it, and even some other Archey forks.
So I guess such a feature was definitely missing here (?).

## How has this been tested ?

Locally, with `flameshot`, `scrot`, `import` (ImageMagick) & `gnome-screenshot`.

## Types of changes :

- Bug fix (non-breaking change which fixes an issue)
- Typo / style fix (non-breaking change which improves readability)
- [X] New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist :

- [X] \[IF NEEDED\] I have updated the _README.md_ file accordingly ;
- \[IF NEEDED\] I have updated the test cases (which pass) accordingly ;
- [X] My changes looks good ;
- [X] I agree that my code may be modified in the future ;
- [X] My code follows the code style of this project ([PEP8](https://www.python.org/dev/peps/pep-0008/)).

### CODE REVIEW

**Comment by HorlogeSkynet** [comment]
That's very clean :+1:

**Comment by ingrinder** [comment]
I noticed on my system (with ImageMagick), sometimes the screenshot was being taken before the output from Archey had appeared, so I've added a fixed delay with a countdown before it's taken. Unfortunately I've tried solutions like forcing the `stdout` buffer to flush but there's no easy way to check when the terminal has actually rendered it, so this was the only thing I could come up with :confused:

**Comment by HorlogeSkynet** [comment]
Other implementations also play with delay features offered by some programs (all of them ?), so I guess that makes sense.
I'm not convinced about the special `print` call flushing output though. I _guess_ we may workaround the issue without it ¯\_ (ツ) _/¯

**Comment by HorlogeSkynet** [comment]
Woops, sorry about my previous message : I didn't get your commit well.
I'm all good with latest changes, this piece of code will evolve for sure in the near future anyway. We definitely need more feed-backs from end-users :ok_hand:

I took the liberty to remove one your `print`-ed message ; I _think_ we can keep Archey quiet if the passed command got executed well :man_shrugging:

**Comment by ingrinder** [comment]
Ah yes, sorry, that sneaked in my last commit while I was figuring out what was taking the screenshot on my system -- For some reason in VS Code under XWayland, some of the environment variables are set wrong (I think it was `XDG_CURRENT_DESKTOP`) and the screenshot from `gnome-screenshot` is black... But I think this is a VS Code issue rather than anything to do with us!

As you say, I'm sure we'll be refining this implementation in future regardless :smiley:

**Comment by HorlogeSkynet** [comment]
Well that's indeed weird, good luck with the investigation :open_mouth:

**Pull request merged**
