### PR TITLE
[WIP] Moved Entry Class Definitions to Seperate Files

### PR DESCRIPTION
**Pull request by lannuttia**
I separated sections of the code into separate files.

## Reason and / or context
I made these changes in order to improve modularity of the code.

## How has this been tested ?
I have been testing that everything still works by running the program periodically in my host OS (Arch Linux) as I made changes.

### CODE REVIEW

**Comment by HorlogeSkynet** [comment]
Hey back @lannuttia !

I've just pushed some changes to make the (new) core code compatible against Pylint.

The following is still to do / change / discuss :

* [ ] Are default values for class parameters really needed ?
* [ ] Shouldn't we now make `Configuration` a singleton and use it directly in the concerned classes, instead of loading it as a global variable in the main module ?
* [ ] Rework the tests suite to make it pass (`python3 setup.py test`)
* [ ] Make the `test/` suite compatible against Pylint too.
* [ ] **Most importantly**, we have to figure out a way to "distribute a built version" of the script (as the `archey/archey.py` current _master_ script).
Whereas exploding the project into multiple modules could make things more readable on a development side, I think @djmelik initially wrote Archey with some _ease of use_ ideas for users, and  [it would be a good point to keep things like this](https://blog.samuel.domains/blog/articles/the-archey-project-what-i-ve-decided-to-do).
WEB front projects usually propose some compiled and minified versions of their assets under a `dist/` folder, I wonder if something similar could be achieved here, in Python.
Or maybe add instructions about wheel building or so ?

@AdJaGu @normcyr @Si13n7 if you guys have any opinion on the subject, we would be pleased !

:wave:

**Comment by lannuttia** [comment]
Before I voice my opinion on this, I think it is worth mentioning why I was originally drawn to separating the code out into modules. I was looking at adding a command line argument parser (argparser to be exact) at some point so the user could specify a config file via the command line instead of being required to have a config file in one of the three currently hard coded locations. I thought it would be easier to manage the addition of a command line argument parser if everything was modular and I was able to remove direct use of the configuration singleton from all of the classes.

#### On the topic of the Configuration singleton:
Like I have mentioned above, I removed direct use of the global configuration singleton from  the classes in order to facilitate the addition of a command line argument parser and addition of an argument that would allow user specification of a config file.

 #### On the topic of default values
While the default values should currently not be used, I thought it was a good idea to hard code some default value so if someone was to modify the configuration files and remove all mentions of the options, there was still some kind of default value specified.

While I am reflecting on how the options are retrieved from the configuration singleton, I believe that in order to make use of the default options in the way that I intended, we would need to modify how we index into the configuration instance to get the options.

With all of that being said, I am not strongly opinionated on whether or not we keep default values for the key word arguments.

If I can make a suggestion, I was wondering if we really needed entry class instances. Now that everything is separated out into modules, I think it would be cleaner to replace the class definitions with functions. This would allow us to get the value that should be displayed without needing to access a "magic" class member.

#### On the topic of distribution
I currently don't have any experience distributing python projects let alone distributing python projects with a build step so I'm afraid I won't be able to offer much help there.

**Comment by HorlogeSkynet** [comment]
I'm currently working on the tests... WIP.

---

About building a standalone _dist_ script : http://blog.ablepear.com/2012/10/bundling-python-files-into-stand-alone.html

BUT, atm, we can't run `python3 archey/`...

---

Can't we define `{DE,WM}_DICT` constants directly in their respective modules, as they are not used anywhere else ?

---

About moving from classes to functions, this would fix [this](https://github.com/HorlogeSkynet/archey4/blob/13aba3a46276adee3dd85ad3d660140806a105c7/.pylintrc#L15), and would allow us to avoid using `value` attributes.

---

More things to come woon, :wave:

**Comment by HorlogeSkynet** [comment]
So here is another check-list about what is ongoing / still to be discussed :

* [ ] About default parameters and configuration singleton : What if we make `Configuration` static ([one of these ways](https://stackoverflow.com/questions/6760685/creating-a-singleton-in-python) for instance), and directly use `argparse` there ?  
The main would load this module, and `argparse` would run its routine.  
Later, the `configuration` module would be "imported" by the others, and they would retrieve the needed values from the singleton.  
This way, we wouldn't have to specify any "default" value for classes parameters, and the _modular_ aspect you wanted might be reached.

* [ ] About distributing, I fear the method I pointed to above would end up in a very heavy binary "ZIP-like" file, and thus it wouldn't really fit in a source repository like this.  
I've been thinking we could rather add a little procedure in the README, explaining to the user / sysadmin how he could "build" a standalone version, direclty from sources.  
**BUT**, I can't manage to make the method working, and this is a priority before merging this.

* [ ] Replacing class by regular functions ? IMHO, not really an _issue_ atm, and we could keep the original "syntax" of the project.

* [ ] What about defining `{DE,WM}_DICT` constants directly in their respective modules, as they are not used anywhere else ?

I'm waiting for your input / opinions on this, bye :wave:

**Comment by lannuttia** [comment]
After reading the linked SO thread, I think that using the Configuration singleton as a metaclass (method #3 in the thread) would be sufficient for providing the modularity I wanted . I also think that moving the {DE,WM}_DICT constants to their respective modules would be a worthwhile change.

**Comment by HorlogeSkynet** [comment]
So I think we are good over here, at least from an architecture / logic point of view.

---

I have caught a glimpse of the distribution "issue" with [StickyTape](https://github.com/mwilliamson/stickytape) ([once it is fixed with our case](https://github.com/mwilliamson/stickytape/pull/5)), but it appears to be failing with :

```
ModuleNotFoundError: No module named '__main__.output'; '__main__' is not a package
```

... which is the same error encountered when running `python3 archey/__main__.py` directly, which is itself related to another error occurring with `python3 archey/` (supposed to work), due to relative imports within the package.

That very issue prevent us from trying [this procedure](http://blog.ablepear.com/2012/10/bundling-python-files-into-stand-alone.html) procedure too...

I don't know whether we should merge this while these executions are not working as expected...
What do you think about that ?

++ :wave:

**Comment by HorlogeSkynet** [comment]
Up @lannuttia !

It would be good to merge and draft a v4.7.0 during July.
This [StackOverflow thread](https://stackoverflow.com/questions/16981921/relative-imports-in-python-3) explains very well the issue we are facing.
Although, I'm not very keen about tweaking the `PYTHONPATH`, as often seen.

Bye :wave:

**Comment by HorlogeSkynet** [comment]
Hey back @lannuttia !

With previous changes, the PR now LGTM.
Could you tell me whether it fits your initial thoughts/work ? (I had to replace relative imports by absolute ones back, it was messy...)
I was planning to (finally) merge it within two or three weeks, but it would be very cool if someone could try this out now.

(Don't mind the Travis Python 3.8 job failing, apparently due to `unittest.mock` ; it definitely need further investigations when testing against this new version [although it appears Pylint does not support it at all yet)

Bye :wave:

**Comment by lannuttia** [comment]
I'm happy with the changes that have been made. I think these changes hold true to what I had in mind. With the addition of the packaging and CI fixes I just pushed, I think everything LGTM too.

**Pull request merged**
