### PR TITLE
CPU bug fix for some ARM architectures, documentation styles and version bumping

### LINKED ISSUE #29: Script crashes in CPU class on ARM-based installs
## Expected behavior

The archey script will run and display CPU information.

## Current behavior

Archey crashes with the following traceback:
```
[petracvv@archrock lib]$ archey
Traceback (most recent call last):
  File "/usr/bin/archey", line 1081, in <module>
    main()
  File "/usr/bin/archey", line 1075, in main
    output.append(key.name, key.value().value)
  File "/usr/bin/archey", line 836, in __init__
    re.search('(?<=model name\t: ).*', file.read()).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```
## Possible solution

Parse the `lscpu` program output instead of `/proc/cpuinfo` output as the output of `/proc/cpuinfo` is much less informative on ARM architectures.

Example output of `/proc/cpuinfo` on my hardware:
```
[petracvv@archrock lib]$ cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4
```

Example output of `lscpu`:
```
[petracvv@archrock lib]$ lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         1296.0000
CPU min MHz:         408.0000
BogoMIPS:            48.00
L1d cache:           unknown size
L1i cache:           unknown size
L2 cache:            unknown size
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
```
## Your environment

* Version used (4.x.y) :  4.4.0
* Hardware type (Laptop, Server, Raspberry, ...) :  Rock64 ARM64 board
* Operating System and version :  ArchARM using a aarch64 build
* Environment name and version : 
* Connectivity (Off-line, LAN only, Internet access, ...) : Internet access

### PR DESCRIPTION
**Pull request by HorlogeSkynet**
Hi everyone !

## Description

Not much more than the title above.

## Reason and / or context

- [X] Would close #29 if @petracvv is OK with it.

## How has this been tested ?

* Debian 10
* Tests cases !

## Types of changes :

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Typo / style fix (non-breaking change which improves readability)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist :

- [X] My change looks good ;
- [X] I have updated the test cases (which pass) accordingly ;
- [X] I have updated the _README.md_ file accordingly ;
- [X] I agree that my code may be modified in the future ;
- [X] My code follows the code style of this project ([PEP8](https://www.python.org/dev/peps/pep-0008/)).

### CODE REVIEW

**Comment by petracvv** [comment]
Awesome, thanks! Looks like this is working:

```
[petracvv@archrock archey4]$ git branch
* fix/arm_cpu_model_name
  master
[petracvv@archrock archey4]$ python build/lib/archey/archey.py 

               +                 User: petracvv
               #                 Hostname: archrock
              ###                Model: Not detected
             #####               Distro: "Arch Linux" aarch64
             ######              Kernel: 4.16.8-1-ARCH
            ; #####;             Uptime: 20 minutes
           +##.#####             WindowManager: Not detected
          +##########            DesktopEnvironment: Not detected
         #############;          Shell: /bin/bash
        ###############+         Terminal: xterm-256color ## ## ## ## ## ## ##
       #######   #######         Packages: 293
     .######;     ;###;`".       Temperature: 53.3 C (Max. 53.3 C)
    .#######;     ;#####.        CPU: Cortex-A53
    #########.   .########`      GPU: Not detected
   ######'           '######     RAM: 104 MB / 3983 MB
  ;####                 ####;    Disk: 1 GB / 31 GB
  ##'                     '##    LAN_IP: 192.168.1.205
 #'                         `#   WAN_IP: 98.227.81.177
```

**Comment by HorlogeSkynet** [comment]
Thanks Mihai ! Let's now wait for contributors' approvals 😉

Tip : You can disable not detected entries in your configuration.

**Comment by HorlogeSkynet** [comment]
Ping @AdJaGu @Si13n7, it would be very cool if you had some minutes to spare for this :slightly_smiling_face:

**Comment by HorlogeSkynet** [comment]
Has been force-merged due to more 15 days of frozen state.

**Pull request merged**
