### PR TITLE
[GPU] Adds support for Raspberry Pi (VideoCore chipsets)

### PR DESCRIPTION
**Pull request by HorlogeSkynet**
See #130.

## How has this been tested ?

Unit tests and Raspberry Pi 1 (running as root).

## Types of changes :

-  Bug fix (non-breaking change which fixes an issue)
- Typo / style fix (non-breaking change which improves readability)
- [X] New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist :

- \[IF NEEDED\] I have updated the _README.md_ file accordingly ;
- [X] \[IF NEEDED\] I have updated the test cases (which pass) accordingly ;
- \[IF BREAKING\] This pull request targets next Archey version branch ;
- [X] My changes looks good ;
- [X] I agree that my code may be modified in the future ;
- [X] My code follows the code style of this project ([PEP8](https://www.python.org/dev/peps/pep-0008/)).

### CODE REVIEW

**Comment by MatsA** [comment]
Hi !  Nice ! Please advice how to test. /Mats

**Comment by HorlogeSkynet** [comment]
Sure, first you need to Git clone the project and then checkout the `feat/raspberry_pi_gpu` branch.
From there you can then create a Python virtual environment and install dependencies, before running Archey from sources :

```bash
python3 - m venv venv && source venv/bin/activate
pip install -e .
python3 -m archey
```

Please note that if your configuration isn't "locked" (see `allow_overriding` config option), shipped `config.json` will be preferred over your system/user configuration (if you have any).

Thanks for your time, bye 👋

**Comment by HorlogeSkynet** [comment]
Up @MatsA / @ingrinder :bow:

**Comment by MatsA** [comment]
Sorry, may bad....

Not that good in git cli so googled little and did as below

As said using RPi 5 with desktop

/Mats

git clone -b feat/raspberry_pi_gpu https://github.com/HorlogeSkynet/archey4.git
cd archey4
python3 -m venv venv && source venv/bin/activate
pip install -e .
(venv) pi@test:~/archey4 $ python3 -m archey
                                  User: pi
                                  Hostname: test
          _sudZUZ#Z#XZo=_         Model: Not detected
       _jmZZ2!!~---~!!X##wx       Distro: Debian GNU/Linux 12 (bookworm) aarch64
    .<wdP~~            -!YZL,     Kernel: Linux 6.6.31+rpt-rpi-2712
   .mX2'       _xaaa__     XZ[.   Uptime: 1 hour and 7 minutes
   oZ[      _jdXY!~?S#wa   ]Xb;   Load Average: 0.18 0.07 0.02
  _#e'     .]X2(     ~Xw|  )XXc   Processes: 162
 .2Z`      ]X[.       xY|  ]oZ(   Window Manager: Not detected
 .2#;      )3k;     _s!~   jXf`   Desktop Environment: Not detected
  1Z>      -]Xb/    ~    __#2(    Shell: /bin/bash
  -Zo;       +!4ZwerfgnZZXY'      Terminal: xterm-256color ██ ██ ██ ██ ██ ██ ██
   *#[,        ~-?!!!!!!-~        Packages: (dpkg) 1602
    XUb;.                         Temperature: 60.2 C (Max. 60.4 C)
     )YXL,,                       CPU: 4 x Cortex-A76
       +3#bc,                     GPU: VideoCore VII
         -)SSL,,                  RAM: 390 MiB / 4045 MiB
            ~~~~~                 Disk: 9.4 GiB / 116.8 GiB
                                  LAN IP: 192.168.68.122, fe80::300a:5d35:f089:fc2f
                                  WAN IP: 95.203.190.217
(venv) pi@test:~/archey4 $

**Comment by HorlogeSkynet** [comment]
Thanks for trying ! So I guess GPU detection works, but running as root caused WM & DE to be missing.
Maybe running with sudo would satisfy everyone, but that's another concern.

I'm waiting for @ingrinder review before merging this. Thanks again, bye 👋

**Comment by MatsA** [comment]
> 
> I'm waiting for @ingrinder review before merging this. Thanks again, bye 👋

Hi, nice I could help. Maybe you shouldn't have high hopes for a **ingrinder** response since he haven't been active for half a year..... and a student 😉.... maybe having much other things up and running ? 

/Mats

**Comment by HorlogeSkynet** [comment]
> Hi, nice I could help. Maybe you shouldn't have high hopes for a **ingrinder** response since he haven't been active for half a year..... and a student 😉.... maybe having much other things up and running ?

Indeed, I hope he's okay.
Unfortunately he's the only other maintainer here, and I usually prefer multiple positive reviews before merging something (mostly when it's my own code :upside_down_face:).
We're already late for the v4.15 release, I plan to wait until the end of the month before merging everything and eventually releasing it.

Bye :wave:

**Comment by HorlogeSkynet** [comment]
(branch has been rebased and AppArmor profile extended according to new opened/read files)

**Pull request merged**
