### PR TITLE
[PACKAGES] Add support for FreeBSD & OpenBSD

### PR DESCRIPTION
**Pull request by ingrinder**
## Description

Simply adds the OpenBSD and FreeBSD package managers to the entry so it works.

## Reason and / or context

See #69.

## How has this been tested ?

On fresh virtual machines.

## Types of changes :

- Bug fix (non-breaking change which fixes an issue)
- Typo / style fix (non-breaking change which improves readability)
- [X] New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist :

- \[IF NEEDED\] I have updated the _README.md_ file accordingly ;
- [X] \[IF NEEDED\] I have updated the test cases (which pass) accordingly ;
- [X] My changes looks good ;
- [X] I agree that my code may be modified in the future ;
- [X] My code follows the code style of this project ([PEP8](https://www.python.org/dev/peps/pep-0008/)).

### CODE REVIEW

**Comment by ingrinder** [comment]
Oh! Tests! Oops... It's about time I go to bed now, let me convert this to draft and I'll fix that tomorrow :smile:

**Comment by HorlogeSkynet** [comment]
No worries ! I took the liberty to simplify writing tests for this entry, hoping it will (**DRY** and) help you add the missing ones tonight :sweat_smile:

**Comment by ingrinder** [comment]
Ah... I just rewrote the package tests for this before pulling your changes... We made very, very similar changes 😆

I've pushed them to bsd_support/packages_alt, perhaps we could merge them together?

Meanwhile, I'll add the required tests here too 👍

**Comment by HorlogeSkynet** [comment]
Oh sorry... There was some concurrency in our flow 🙄
I'll be honest too, I also prefer mine ; no offense.

Although, I _might_ have noticed an inconsistency.
For `pkg` you've set the `skew` to `1` but your test output does not contain any, and actually got 7 entries (instead of 6) !
Did you omit a line in the mocked output ?

Thanks, see you 👋

**Comment by ingrinder** [comment]
Yeah, sorry about that, I was a bit cheeky and since my BSD installations have ~150 packages each I didn't fancy adding in an extra 300 lines to the test just for those...! Each of those lists was simply the first 6/7 packages listed in each output.

I went about installing two fresh copies and I've now put their far more minimal outputs into the tests so they're more correct :+1:. You can see the `pkg` test correctly ignores `pkg` itself from the output.

**Comment by HorlogeSkynet** [comment]
> Yeah, sorry about that, I was a bit cheeky and since my BSD installations have ~150 packages each I didn't fancy adding in an extra 300 lines to the test just for those...! Each of those lists was simply the first 6/7 packages listed in each output.

No problem ! All the other tests are actually only partial outputs too, to avoid really-really-really-long irrelevant lists...

> I went about installing two fresh copies and I've now put their far more minimal outputs into the tests so they're more correct 👍. You can see the `pkg` test correctly ignores `pkg` itself from the output.

I'm not sure about _ignoring_ `pkg` itself 🤔 😂
I mean, if it is an installed package, that may receive updates (or even be removed), why shouldn't we count it ?
The same situation may occur against other package managers, but we actually don't take it into consideration right now 🙄
It's not a major issue, but I think we should take advantage of this to clarify how we are supposed to handle it. Tell me what you think about that !

**Comment by ingrinder** [comment]
> I mean, if it is an installed package, that may receive updates (or even be removed), why shouldn't we count it ?

Ohhh!, I've misinterpeted the comment in `packages.py`:
```python
# If any, deduct output skew present due to the packages tool.
```

I thought this meant the package manager itself was deducted from the count - but this actually means any skew due to the formatting of the output, right? So, I assume all the other package managers already include themselves if they are listed? That does make sense, like you say they are indeed packages with versions that can be updated and such. We should probably still treat them as a package in our count, then. Sorry for the mix-up! 😄 

Assuming we're following this pattern, that removes the skew from `pkg` entirely - I'll change it now 😁

**Pull request merged**
