### PR TITLE
IPv6 support, and maximum number of LAN addresses

### PR DESCRIPTION
**Pull request by Si13n7**
## Description

IPv6 should be supported; and defining the maximum number of LAN addresses can be very useful, if word wrapping is enabled it doesn't look so nice with many addresses.

Both settings are optional features!

## Types of changes :

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Typo / style fix (non-breaking change which improves readability)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist :

- [x] My change looks good ;
- [ ] I have updated the _README.md_ file accordingly ;
- [x] I agree that my code may be modified in the future ;
- [x] My code follows the code style of this project ([PEP8](https://www.python.org/dev/peps/pep-0008/)).

### CODE REVIEW

**Comment by HorlogeSkynet** [comment]
Hi Roy !

Thanks for this, I'll review the whole thing "soon".
I'll keep you posted, nevertheless quickly it looked good 😉

Cheers

**Comment by Si13n7** [comment]
Hey Samuel!

I was a little bit to early with a pull reques.
I have found 2 critical issues.

**Issues:**
- If IPv6 support is disabled, self.value wasn't defined
- The new config settings must be set, so we need to add them to the default config so that archey4 works without a config.json

**Comment by HorlogeSkynet** [comment]
Hey Roy !

Yeah I was just looking at this and that was the first thought I've had 🙁
I go back on it, but I don't have an IPv6 address here to test... I'll figure something out !

I'll keep you posted 👌

**Comment by HorlogeSkynet** [comment]
Okay I've rework many things about your changes, could you allow me to push to your branch if you don't mind ?

**Comment by Si13n7** [comment]
I have added you as collaborator 😉

**Comment by HorlogeSkynet** [comment]
For previously (sorry for the delay), as your repo is a fork of this one, it looks like I can push to your branch opened as PR without accepting the invitation you sent me (I didn't know about that at all, it's pretty impressive).

ANYWAY, I've finally pushed some stuffs, tell me if it's OK with you, and of course, don't hesitate to re-modify afterwards if you want !

Cheers

**Comment by Si13n7** [comment]
I have tested your code. There is a little blemish in comparison with LAN. In general, the LAN method will get IPv4 as first, followed by IPv6. So it's a bad idea to turn this over for WAN.

**Output before:**

| Key  | Value |
| ------------- | ------------- |
| LAN_IP  | ipv4, ipv6  |
| WAN_IP  | ipv4, ipv6  |

**Output now:**

| Key  | Value |
| ------------- | ------------- |
| LAN_IP  | ipv4, ipv6  |
| WAN_IP  | ipv6, ipv4  |

**Comment by HorlogeSkynet** [comment]
Yeah of course we can swap again these two values, only line 889 is concerned 😉

**Comment by Si13n7** [comment]
Yeah I see, great! 👍

**Comment by HorlogeSkynet** [comment]
Your latest table makes me think a lot about IPv6 local addresses :

* The manual of `hostname` tells :
```
       -I, --all-ip-addresses
[...]
The loopback and IPv6 link-local addresses are omitted.
[...]
```

* With the current "manual way", they are not displayed either (`grep` filters out `'local '` only, not `'local6 '`).

What do you think about this ?

**Comment by Si13n7** [comment]
After a couple of tests, i have found out that we have to change `'inet '` to `'inet\|inet6 '` in `line 828`. Then i get a similar output with the "manual way", including IPv6 addresses.

**Comment by HorlogeSkynet** [comment]
Yeah a better way would be to user ``grep -E 'inet6? '`, but we wouldn't get this result with `hostname -I`.
It'd be a little "awkward" to get different output depending on the methods. So I'm confused :confused:

**Comment by Si13n7** [comment]
I get all addresses with `hostname -I`, including all IPv6 addresses . . .

**Comment by HorlogeSkynet** [comment]
Wow wow... (I understand now your previous posts then 😜)

See in my case :

image

So I think we have a different configuration...
Could you tell me what is the scope of your IPv6 address(es) ?

**Comment by Si13n7** [comment]
unbenannt-2

**Comment by HorlogeSkynet** [comment]
Oh okay I understand now... 
Last thing not very clear, why `hostname -I` outputs IPv6 addresses with a `global scope` in your cases, as the manual tells the opposite ? 😖

**Comment by Si13n7** [comment]
I think the different is that i have also real IPv6 addresses. You said you have no IPv6 connection, so maybe your local IPv6 addresses are unnecessary for hostname.

**Comment by HorlogeSkynet** [comment]
Yeah it's exactly that, but my point is that does not account for what is said in the `hostname`'s manual 🤔

**Comment by HorlogeSkynet** [comment]
Okay, here we are. I've tried something. Now your Archey output with the two methods is supposed to be the same. Could you confirm it ? 🙂

Second question, you don't mind if I squash and merge the whole thing up when you'll be OK ? 🤔

Thanks !

**Comment by Si13n7** [comment]
Great, it works very well! 😉

**Comment by HorlogeSkynet** [comment]
Perfect, glad to hear that 👌

You're OK for a final merge then ? 🙂

**Comment by Si13n7** [comment]
Yes, of course! 👍

**Comment by HorlogeSkynet** [comment]
Hey Roy @Si13n7 !

You don't mind if we wait for next upcoming changes (maybe ?) before drawing a new release with this very rework previously merged ?

Just tell me if you do, I'd create a `v4.3.2` and re-package the whole thing ASAP 😉

Bye 👋

**Comment by Si13n7** [comment]
Hey Samuel,
do you mean the last changes in my fork? Merged with your updates, few minutes ago. I can create a pull request, if you want. It works very well, maybe you have some ideas to improve the code, I'm not very experienced with Python.
Cya 😄

**Comment by HorlogeSkynet** [comment]
Hi back !

Oh 🤣 No I meant those about this very PR 😂

But with your latest, once we'll have talked about them, I'll draw a release 😜

Create a new PR when you'll be ready, no stress. I'd review this during the week. Cya 👋

**Comment by Si13n7** [comment]
Ah okay... 😆 No, I don't mind if we wait for next upcoming changes. 😉 In general, I don't care, I always use the latest version, public release or not. 😜 So you can take your time, it's your choice when you draw a new version. I'm fine with it. 😉

**Comment by HorlogeSkynet** [comment]
Perfect thanks again, I just wanted to verify I was not bothering someone 😂

++ 👋

**Pull request merged**
