### PR TITLE
Adding IP addresses (both LAN and WAN) info to archey4

### PR DESCRIPTION
**Pull request by normcyr**
I added the possibility to extract both the LAN and WAN IP addresses of the system to the output of Archey4. 

(also changed the screenshot in README to reflect those additions)

### CODE REVIEW

**Comment by HorlogeSkynet** [comment]
Hey !

Thanks for that, it's being late over here, but tomorrow I'll review and merge your changes 😉
This looks pretty OK for me, I'd just do some tests and update the screenshot on my blog post instead of uploading it on this repo' (if you are OK with that ?).

See you 👋

**Comment by normcyr** [comment]
Awesome. I thought IP addresses were relevant information to extract when you're on the move (not so much with desktops, but the options can be commented out). 

Regarding the screenshot, I knew it was not the best idea to have it in a branch in my repo. I figured you'd get it and move it somewhere more "permanent". If you prefer to change it to reflect your stats, I won't be offended :wink:. I just wanted to present a more complete pull request with modifications to the README as well.

Cheers!

**Comment by HorlogeSkynet** [comment]
Re' !

So this is what I got : https://github.com/HorlogeSkynet/Archey4/tree/review/normcyr_ip-adresses
Tell me what you think about that, and feel free to do some more tests 😉

**Comment by HorlogeSkynet** [comment]
Actually, I've let the `dig` method in the first place 'cause it's 6x faster 😮

**Comment by normcyr** [comment]
You've modified it in an elegant way with error handling etc (I am still new to Python). 

The only "problem" is that the command `hostname -I` returns 2 IP addresses in my case. This is why I used the regex trick. Not a big issue...

And thanks for the credit :wink:

**Comment by HorlogeSkynet** [comment]
Yeah, but I've checked the man page about that, it's said that _loopback_ IP is supposed to be ignored with `-I`, so if you have 2 IPs present within the output, it may be relevant to keep both 😛

I'll merge, do some replacements and release the v4.1.0, watch the repo' 😉

**Comment by normcyr** [comment]
Sounds good! Thanks for the prompt replies.

**Comment by HorlogeSkynet** [comment]
It's okay, when it's during the day, you may expect that 👌

**Comment by normcyr** [comment]
Oh you're right, the second IP address is also important. In fact, `hostname -I` returns both LAN IP addresses (wired and wireless). I forgot I was connected to both!

**Comment by HorlogeSkynet** [comment]
Merged with aa43e7737f925a45411c03c1faa22c68e922cc02

**Pull request closed without merging**
