### PR TITLE
[UPTIME] Logs `uptime` errors at warning level

### LINKED ISSUE #132: [BUG] uptime: /dev/ttys010: No such file or directory
**Describe the bug**
When launching archey, this message is shown at the very beginning output:
```
uptime: /dev/ttys010: No such file or directory
```

**Expected behavior**
Not show this error.

**Screenshots**
image

**Environment**

 - Version used (4.X.Y.Z) : 4.14.1.0
 - Method of installation (distribution package, PyPI, Homebrew, sources) : homebrew
 - Hardware type (laptop, server, Raspberry, hyper-visor) : Macbook Air M2
 - Python version (3.Y.Z) : Python 3.11.3
 - Operating system and version : macOS Ventura 13.3.1 (22E261)
 - Graphical environment name and version : --
 - Connectivity (off-line, LAN only, Internet access) : LAN/Wifi/Internet

**Additional context**

**Custom configuration**

<details><summary>Custom configuration</summary>
<p>

```json
{
	"allow_overriding": true,
	"parallel_loading": true,
	"suppress_warnings": false,
	"entries_color": "",
	"honor_ansi_color": true,
	"logo_style": "retro",
	"entries": [
		{ "type": "User" },
		{ "type": "Hostname" },
		{ "type": "Model" },
		{ "type": "Distro" },
		{
			"type": "Kernel",
			"check_version": false
		},
		{ "type": "Uptime" },
		{
			"type": "LoadAverage",
			"decimal_places": 2,
			"warning_threshold": 1.0,
			"danger_threshold": 2.0
		},
		{ "type": "Processes" },
		{ "type": "WindowManager" },
		{ "type": "DesktopEnvironment" },
		{ "type": "Shell" },
		{
			"type": "Terminal",
			"use_unicode": true
		},
		{ "type": "Packages" },
		{
			"type": "Temperature",
			"char_before_unit": " ",
			"sensors_chipsets": [],
			"sensors_excluded_subfeatures": [],
			"use_fahrenheit": false
		},
		{
			"type": "CPU",
			"one_line": false,
			"show_cores": true
		},
		{
			"type": "GPU",
			"one_line": false,
			"max_count": 2
		},
		{
			"type": "RAM",
			"warning_use_percent": 33.3,
			"danger_use_percent": 66.7
		},
		{
			"type": "Disk",
			"show_filesystems": ["local"],
			"combine_total": true,
			"disk_labels": null,
			"hide_entry_name": null,
			"warning_use_percent": 50,
			"danger_use_percent": 75
		},
		{
			"type": "LAN_IP",
			"one_line": true,
			"max_count": 2,
			"show_global": false,
			"ipv6_support": false
		},
		{
			"type": "WAN_IP",
			"one_line": true,
			"ipv4": {
				"dns_query": "myip.opendns.com",
				"dns_resolver": "resolver1.opendns.com",
				"dns_timeout": 1,
				"http_url": "https://v4.ident.me/",
				"http_timeout": 1
			},
			"ipv6": {
				"dns_query": "myip.opendns.com",
				"dns_resolver": "resolver1.opendns.com",
				"dns_timeout": 1,
				"http_url": "https://v6.ident.me/",
				"http_timeout": 1
			}
		}
	],
	"default_strings": {
		"latest": "latest",
		"available": "available",
		"no_address": "No Address",
		"not_detected": "Not detected",
		"virtual_environment": "Virtual Environment"
	}
}
```

</p>
</details>

### PR DESCRIPTION
**Pull request by HorlogeSkynet**
`uptime` STDERR will now be read and each line will be emitted as a warning log. This allows macOS users experiencing "uptime: /dev/ttysXXX: No such file or directory" errors to silence them using configuration (instead of silently dropping them).

> closes #132

## How has this been tested ?

It hasn't (_EDIT_ on a affected macOS system).

## Types of changes :

- [X] Bug fix (non-breaking change which fixes an issue)
- Typo / style fix (non-breaking change which improves readability)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist :

- \[IF NEEDED\] I have updated the _README.md_ file accordingly ;
- \[IF NEEDED\] I have updated the test cases (which pass) accordingly ;
- \[IF BREAKING\] This pull request targets next Archey version branch ;
- [X] My changes looks good ;
- [X] I agree that my code may be modified in the future ;
- [X] My code follows the code style of this project ([PEP8](https://www.python.org/dev/peps/pep-0008/)).

### CODE REVIEW

**Comment by HorlogeSkynet** [comment]
Up @ingrinder 😇

**Review by ingrinder — APPROVED** [review]
All LGTM! Apologies for missing this one for a while!

> How has this been tested ?
> It hasn't.

The tests pass and it runs okay on my system so that counts in my view :grin:

**Comment by MilesTEG1** [comment]
Hello,
Is there a fix in the pipe?
I still have this error when archey start, on macOS Sonoma.
CleanShot 2023-10-02 at 08 56 20@2x

**Comment by HorlogeSkynet** [comment]
Hello, the (this) fix is already out of the pipe. You can enable the `suppress_warnings` option to hide it.
Bye 👋

**Comment by MilesTEG1** [comment]
Oh my !
Thanks very much 😃

**Pull request merged**
