### PR TITLE
Drops `lsb-release` usage, adds SlackWare & Improves code styles

### PR DESCRIPTION
**Pull request by HorlogeSkynet**
Hey everyone !

## Description

So basically, this is what this PR bring to Archey :

* SlackWare support, any feedback would be appreciated
* Version bumping, as we would drop `lsb_release` usage, by replacing it with `distro` maintained Python module, as discussed in #36
* Forces IP version to use for `WAN_IP`, regarding `wget` & `dig` calls
* Code styles (as always). Now conforming to `bad-continuation` PyLint warning :tada:
* Better distributions support, as "matching" should be better, including the new introduced `distro` usage
* An up-to-date contributors list :slightly_smiling_face:

## Reason and / or context

As @eli-schwartz reported in #36, `/etc/os-release` should definitely be used instead of calling external `lsb_release` script. This way, Archey would not depend anymore on its various implementations and would be less difficult to install on Fedora for instance.

This is not really BC, as `python3-distro` is not available on Debian Jessie.
Thus, the documentation has been updated so as to notice the users to opt for a `pip` installation (the `distro` module would be downloaded by `pip`, and not breaking Debian packages ecosystem).

Nevertheless, still looking forward to gathering some thoughts from you guys, and from @eli-schwartz of course (mostly during packages releases :relieved:).

## How has this been tested ?

Test cases, Debian Buster, Debian Jessie (at the moment of writing).

## Types of changes :

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Typo / style fix (non-breaking change which improves readability)
- [x] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist :

- [X] \[IF NEEDED\] I have updated the _README.md_ file accordingly ;
- [X] \[IF NEEDED\] I have updated the test cases (which pass) accordingly ;
- [X] My change looks good ;
- [X] I agree that my code may be modified in the future ;
- [X] My code follows the code style of this project ([PEP8](https://www.python.org/dev/peps/pep-0008/)).

---

EDIT : The documentation of the `distro` module is available [here](https://distro.readthedocs.io/en/latest/).

### CODE REVIEW

**Comment by Si13n7** [comment]
Hey, little late because of holidays... 😄 

There is some trouble on my Ubuntu machines:
```
Traceback (most recent call last):
  File "archey.py", line 13, in <module>
    import distro
ImportError: No module named 'distro'
```

**Comment by HorlogeSkynet** [comment]
Hey ! No problem, this is the wort part of the year for FOSS :joy:

This will be added to the release notes ; Dependencies have changed :

```diff
- lsb-release
+ python3-distro
```

If you run a 16.04+ distribution, you should be able to install it directly with APT.
Else, you'd want to go with PIP... `pip3 install distro`

Have a good evening Roy, keep me up to speed :ok_hand:

**Comment by HorlogeSkynet** [comment]
Thanks for this ! Are we OK with your WSLs too ? :roll_eyes:

**Comment by Si13n7** [comment]
Yeah, I'll always test WSL! 🙄 Everything is fine! 😉

Sorry, I was too lazy to write that down yesterday. I thought after the last reviews it would be clear that I'll always test several systems...

**Test Environments (minimum):**
- Kali GNU/Linux Rolling (WSL)
- Ubuntu 16.04 LTS (WSL)
- Ubuntu 16.04 LTS (desktop)
- Ubuntu 18.04 LTS (server)

_(all environments support IPv6 as well)_

So, if I don't write anything else in the future, you can be sure that I tested it on all these systems! 😜

**Comment by HorlogeSkynet** [comment]
Ahhh perfect, sorry for having doubt about that ; Let's say it is because of holidays 😌

So the PR is okay, I'll merge this when able to build all packages... Maybe during this WE.

++

**Pull request merged**
