### PR TITLE
Implement feature request #57

### PR DESCRIPTION
**Pull request by ingrinder**
## Description
Implemented rearrange feature requested in #57 along with some other code changes to enable more configurability in future.

Please **carefully read the changes in the commits** as I have **removed some features from the configuration code** in the name of simplicity, as in my opinion these are unnecessary. If requested I can revert these changes for this PR, however I think they are overall for the better.

## Reason and / or context
* Implements feature request #57 - ability to rearrange entries.
* Simplifies codebase somewhat.
* Tidies configuration file and logic behind configuration files.
* Increases output customisability for entries.

## How has this been tested ?
Code in this PR has been tested on one machine and appears to work with the same behaviour as previously (overall behaviour change is minimal).

**TODO**: Some new tests are yet to be written for the new behaviour changes/additions that add more cases to cover.

## Types of changes :

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Typo / style fix (non-breaking change which improves readability)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist :

- [x] I have updated the _README.md_ file accordingly ;
- [ ] \[TODO\] I have updated the test cases (which pass) accordingly ;
- [ ] My changes looks good ;
- [X] I agree that my code may be modified in the future ;
- [X] My code follows the code style of this project ([PEP8](https://www.python.org/dev/peps/pep-0008/)).

### CODE REVIEW

**Comment by ingrinder** [comment]
Does anyone have any idea what's going on with these tests since the configuration modification? I'm at a complete loss, this behaviour doesn't seem to make any sense to me.

**Comment by HorlogeSkynet** [comment]
Give me some more days and I'll come back to you with proper reviews for current opened issues and PRs :ok_hand:
Thanks for all :100:

**Comment by ingrinder** [comment]
Right now the builds on travis are failing because stickytape no longer works since the changes I made to importing entries. I'm not entirely sure how to deal with this aside from dirtying up the top-level namespace by importing all of the entries... For now, I've opened issue mwilliamson/stickytape#12 about this behaviour.

**Comment by HorlogeSkynet** [comment]
I am leaving a quick comment here as it seems you are spending _a lot_ of time on these "features".

My thoughts are :

* It looks like yet-another-rework, and we are just getting out of one (#41) :fearful: ;
* I understand Archey3 ~~provides~~ provided a bunch of features compared to the original Archey, but when I "took over" this in 2017, I deliberately wanted to keep things simple (and stupid) and, mostly, **maintained** (mainly by endorsing a "bug fixer" role) (see [here](https://blog.samuel.domains/archey4)) ;
* My point is, we will be dealing with huge backward compatibility issues, mainly about the configuration file/entries...
* This means we _would_ have to handle the "old" format, as long as the "new" one, and I definitely don't wanna go down this road, as we only know when it starts, never like it ends (`/api/v{1,2,3,4,5,6,...`) :roll_eyes:
* I haven't yet dug into your changes, but I noticed it required _lots_ of tweaks to keep Stickytape & PyInstaller "working", so I wondered if it's a good idea to break-and-workaround them at all ;
* I don't wanna look or act as """conservative""" here, so please take no offense, and I hope you'll understand my PoV.

Still, I'm looking forward to make Archey correctly handle #55 & #57 in the near future, but without breaking everything would be even better :ok_hand:

Bye :wave:

**Comment by ingrinder** [comment]
Yeah, it's true I've got... let's say *carried away* in this PR. I understand where you're coming from 😅 

There are a few ways I could take this from here.
### Keep going with the PR as it is?
I realise that a lot of the changes have gone far out of scope of just straight-up implementing #55 and #57, so this is probably the worst of the options.
This also kind of goes against your thought of wanting to keep Archey4 simple. Right now, the configuration file is incompatible as you say - I suppose the changes I've made aren't necessary, but I feel that given more configuration options we could end up with a bit of a mess... For our example here implementing #55 and #57, this nets us at least an extra two sections if the current format is kept. If I keep going here, I see one of the following happening with configuration:
1. I revert back to a compatible layout. If the changeable entry names are kept then we end up with a section for configuring the disk entry, a section for ordering entries (perhaps a list of some sort?), and a section for each entry's name. Personally I'm not sure this is the best long-term solution.
2. I keep the layout from 826bdf88d2fa98f0658d87fa2049cec93764d382, and we use post-install scripts on packages to automatically convert any configuration files not in the new format to the new format. This would not be possible with the wheel archives therefore those who installed with `pip` would have to manually update the configuration files. This is probably not the ideal option, though it is probably the only way to introduce the new format without having way too much breakage.
3. We introduce some sort of configuration versioning and- just kidding, this isn't happening, you're totally correct about not going down this route 😃 

#### Split this PR into smaller pieces?
It may also help if a lot of this is broken down into smaller PRs anyway, even if everything is kept the same? This could be a bit more clutter to deal with temporarily, but then it's a little more reasonable having exactly one PR for each feature/change rather than what could be described here as... well, I'll let you fill in that one 🙂 

### Start over
Honestly, if this is the option you'd prefer, I don't mind - please don't feel bad about it! If I start afresh, I suggest keeping 04200a9816e8c0327e485884061d725d0c3d33a0 only (and any of the fixes for the modifications in it), as this essentially provides a framework for easily modifying our entries' output, then:

#55 is implementable by:
* Adding a `disk` configuration section.
* Modifying the `Disk` entry.

#57 is implementable by:
* Adding a section of the configuration for entry ordering - perhaps a list of entries in the preferred order?
* Modifying `Output` to order entries by this configuration option before printing them.

These changes are a lot milder than the huge amount of change in this PR as it stands. 

### Overall
My main thought process behind changing the structure of the configuration file is that we only have a few configurable options at the moment, but given features like the above we might end up with more and more sections of it, further and further from the relevant parts - of course, if the current layout is set in stone now for backwards compatibility reasons, then that's just how it will stay, but

**Comment by HorlogeSkynet** [comment]
Hello Michael !

It's my turn to apologize : Sorry for the delay. I wanted to finish up [some things](https://github.com/HorlogeSkynet/archey4/releases/tag/v4.7.1) before coming back to you on this next matter.

---

So here are my two (six ?) cents :

1. I completely agree with you about 100% of your message ;
2. About "our (best ?) options from there", my thoughts are split between the 2nd & 3rd option ; So let's mix them :
    + We could first implement #55 with the current configuration layout and even actually draft a v4.7.2 shipping this feature ;
    + (Have you already thought about how we would show multiple disks on the same line ?)
    + We could afterwards implement #57 with a new configuration layout (as it's a completely different concern from a functional PoV).
    + v4.8.0 will be our milestone for #57. When we'll get there, I'll do the proper _communication_ announcing the configuration breakage (maybe we could think about a guide or something like that ?). We got **zero** information about the _real_ number of Archey users, and even less about whether or not the configuration is being used (it's actually a rather [_recent_ feature](https://github.com/HorlogeSkynet/archey4/releases/tag/v4.3.0) regarding the real age of this project).
3. Yes, smaller PRs would be appreciated :smile:
4. You've _just_ got a pending invitation to be granted some _push_ rights on this repository. We'll be able to work (together if you want) on branches from the same remote and switch to PRs instantly (+ you'll got the very useful review permission).
5. I'm **not** keen about _dynamic module imports_, I've quickly thought about that lately and I _think_ we won't have to go this way (hence we may keep things simpler + Stickytape & PyInstaller [partly] working) :wink:
6. **NOTE TO OURSELVES FOR THE FUTURE #57** : Register a reference to the `Configuration` singleton in the `Entry` base class (+ makes it abstract !) constructor with the related 'entry' options dictionary. That would DRY all these current identical instantiations.

---

Anyway, thanks again for all, we'll be in touch :ok_hand:
I hope the v4.7.1 (and its minor reworks) won't bother you too much.
Bye :wave:

**Comment by ingrinder** [comment]
Okay, so for now, I'll close this PR. Then:
* I'll make a branch for #55 (only!), and start work on that. I'll leave the PR for it for the moment until it works first 😃. 
  * My idea for multiple disks was partly in the modification of how we handle outputs - since we could override `Entry.output()`, we could append an entry for each disk and have more than one line for the entry if required. We could also offer a configuration option for a single line output? I'll have to see if there's a way to do that neatly.
* Plan to open a branch for #57, right now though I think you're right about focusing on #55 first and we can figure it out later.
* I've also noticed some other things we can work on, I might open issues for these so either of us can start work on them if we want.

Thank you for the collaborator invite! That should hopefully simplify this process a bit (and allow easier collaboration 👍).

**Comment by HorlogeSkynet** [comment]
About :

> My idea for multiple disks was partly in the modification of how we handle outputs - since we could override Entry.output(), we could append an entry for each disk and have more than one line for the entry if required. We could also offer a configuration option for a single line output? I'll have to see if there's a way to do that neatly.

Actually, our biggest problem with this (but it'll also occur with #61 if you want a feature to show multiple `GPU` entries) it's the 18-entry limit, due to how final printing and logos are handled.

There is also an issue with strings that would line-wrap when the terminal happens to be undersized if we decide to write everything as an unique entry (and TBH, it already happens with `LAN_IP` when plenty of IPv6 addresses are present).
I've quickly tried to play with `textwrap.TetWrapper` to imitate [this ~~feature~~ workaround](https://github.com/HorlogeSkynet/archey4/blob/dba5707f436be6dac5dd28810921b9a01298070d/archey/entries/gpu.py#L35) for **each** entry directly in `Output.output` :

```python
text_wrapper = textwrap.TextWrapper(
    width=shutil.get_terminal_size().columns,
    expand_tabs=False,
    replace_whitespace=False,
    drop_whitespace=False,
    placeholder='...'
)
```

... but there is one more delicate issue : ANSI colors characters are counted in final strings lengths, whereas they actually _do not_ take part in width. So... `TextWrapper.fill` perform _wrong_ line-wraps...

:wave:

**Pull request closed without merging**
